Repository tier4/t4-devkit, pull requests merged in 2025-09, with the labels that each got.

#183 test: add sample t4 dataset for unit test
  t4_devkit/common/converter.py
  tests/sample/annotation/attribute.json
  tests/sample/annotation/calibrated_sensor.json
  tests/sample/annotation/category.json
  tests/sample/annotation/ego_pose.json
  tests/sample/annotation/instance.json
  tests/sample/annotation/log.json
  tests/sample/annotation/map.json
  tests/sample/annotation/object_ann.json
  tests/sample/annotation/sample.json
  tests/sample/annotation/sample_annotation.json
  tests/sample/annotation/sample_data.json
  tests/sample/annotation/scene.json
  tests/sample/annotation/sensor.json
  tests/sample/annotation/surface_ann.json
  tests/sample/annotation/vehicle_state.json
  tests/sample/annotation/visibility.json
  tests/sample/data/CAM_BACK/001.jpg
  tests/sample/data/CAM_BACK/002.jpg
  tests/sample/data/CAM_BACK/003.jpg
  tests/sample/data/CAM_FRONT/001.jpg
  tests/sample/data/CAM_FRONT/002.jpg
  tests/sample/data/CAM_FRONT/003.jpg
  tests/sample/data/LIDAR_TOP/001.pcd.bin
  tests/sample/data/LIDAR_TOP/002.pcd.bin
  tests/sample/data/LIDAR_TOP/003.pcd.bin
  tests/sample/status.json
  tests/test_tier4.py
Labels: ci

#186 fix: update to only render crosswalk polygons
  docs/assets/render_map.png
  t4_devkit/viewer/lanelet.py
Labels: bug, documentation

#187 fix: resolve input types of viewer
  README.md
  docs/assets/render_box2ds.png
  docs/assets/render_box3ds.png
  docs/assets/render_pointcloud.png
  docs/install.md
  docs/tutorials/render.md
  t4_devkit/viewer/record/box.py
  t4_devkit/viewer/viewer.py
Labels: bug, documentation

#188 ci: update to run CLI on CI workflow
  .github/workflows/build-and-test.yaml
  tests/conftest.py
  tests/lanelet/test_parser.py
  tests/sample/t4dataset/annotation/attribute.json
  tests/sample/t4dataset/annotation/calibrated_sensor.json
  tests/sample/t4dataset/annotation/category.json
  tests/sample/t4dataset/annotation/ego_pose.json
  tests/sample/t4dataset/annotation/instance.json
  tests/sample/t4dataset/annotation/log.json
  tests/sample/t4dataset/annotation/map.json
  tests/sample/t4dataset/annotation/object_ann.json
  tests/sample/t4dataset/annotation/sample.json
  tests/sample/t4dataset/annotation/sample_annotation.json
  tests/sample/t4dataset/annotation/sample_data.json
  tests/sample/t4dataset/annotation/scene.json
  tests/sample/t4dataset/annotation/sensor.json
  tests/sample/t4dataset/annotation/surface_ann.json
  tests/sample/t4dataset/annotation/vehicle_state.json
  tests/sample/t4dataset/annotation/visibility.json
  tests/sample/t4dataset/data/CAM_BACK/001.jpg
  tests/sample/t4dataset/data/CAM_BACK/002.jpg
  tests/sample/t4dataset/data/CAM_BACK/003.jpg
  tests/sample/t4dataset/data/CAM_FRONT/001.jpg
  tests/sample/t4dataset/data/CAM_FRONT/002.jpg
  tests/sample/t4dataset/data/CAM_FRONT/003.jpg
  tests/sample/t4dataset/data/LIDAR_TOP/001.pcd.bin
  tests/sample/t4dataset/data/LIDAR_TOP/002.pcd.bin
  tests/sample/t4dataset/data/LIDAR_TOP/003.pcd.bin
  tests/sample/t4dataset/map/lanelet2_map.osm
  tests/sample/t4dataset/status.json
  tests/test_tier4.py
  tests/viewer/test_viewer.py
Labels: ci

#185 chore: sync table definition with tier4_perception_dataset
  docs/schema/table.md
  t4_devkit/schema/tables/__init__.py
  t4_devkit/schema/tables/autolabel_metadata.py
  t4_devkit/schema/tables/category.py
  t4_devkit/schema/tables/object_ann.py
  t4_devkit/schema/tables/sample_annotation.py
  t4_devkit/schema/tables/sample_data.py
  t4_devkit/schema/tables/surface_ann.py
  tests/schema/conftest.py
  tests/schema/tables/test_autolabel_metadata.py
Labels: documentation, ci, chore

#191 chore: bump to v0.3.0
  pyproject.toml
Labels: dependencies
