Repository tier4/t4-devkit, pull requests merged in 2025-08, with the labels that each got.

#166 feat: add DB status
  docs/tutorials/cli/t4sanity.md
  t4_devkit/cli/sanity.py
  t4_devkit/common/sanity.py
  t4_devkit/tier4.py
Labels: documentation, new-feature

#173 chore: bump to v0.2.1
  pyproject.toml
Labels: dependencies

#175 feat: add info_filename field to sample_data table
  t4_devkit/schema/tables/sample_data.py
  tests/schema/conftest.py
Labels: new-feature, ci

#176 docs: update document for dataset schema
  README.md
  docs/index.md
  docs/schema/data.md
  docs/schema/index.md
  docs/schema/table.md
  mkdocs.yaml
Labels: documentation

#177 docs: update README
  README.md
  docs/index.md
Labels: documentation

#178 feat: add support of rendering lanelet map
  README.md
  docs/assets/render_map.png
  docs/index.md
  docs/tutorials/render.md
  t4_devkit/helper/rendering.py
  t4_devkit/lanelet/__init__.py
  t4_devkit/lanelet/parser.py
  t4_devkit/tier4.py
  t4_devkit/viewer/lanelet.py
  t4_devkit/viewer/viewer.py
  tests/lanelet/test_parser.py
  tests/sample/map/lanelet2_map.osm
  tests/viewer/test_viewer.py
Labels: documentation, new-feature, ci

#179 feat: add directory path as property
  t4_devkit/tier4.py
Labels: new-feature

#180 refactor: define the method to load tables as function
  t4_devkit/tier4.py
Labels: refactor

#181 style: update typing
  t4_devkit/dataclass/box.py
  t4_devkit/dataclass/trajectory.py
  t4_devkit/dataclass/transform.py
  t4_devkit/viewer/geography.py
Labels: refactor

#182 perf: execute annotation rendering in parallel
  t4_devkit/helper/rendering.py
Labels: refactor
